/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppleRouteImport } from './routes/apple'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as CrashRouteImport } from './routes/crash'
import { Route as MinesRouteImport } from './routes/mines'
import { Route as PlatformsRouteImport } from './routes/platforms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppleRoute = AppleRouteImport.update({
  id: '/apple',
  path: '/apple',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const CrashRoute = CrashRouteImport.update({
  id: '/crash',
  path: '/crash',
  getParentRoute: () => rootRouteImport,
} as any)
const MinesRoute = MinesRouteImport.update({
  id: '/mines',
  path: '/mines',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformsRoute = PlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apple': typeof AppleRoute
  '/conditions': typeof ConditionsRoute
  '/crash': typeof CrashRoute
  '/mines': typeof MinesRoute
  '/platforms': typeof PlatformsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apple': typeof AppleRoute
  '/conditions': typeof ConditionsRoute
  '/crash': typeof CrashRoute
  '/mines': typeof MinesRoute
  '/platforms': typeof PlatformsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apple': typeof AppleRoute
  '/conditions': typeof ConditionsRoute
  '/crash': typeof CrashRoute
  '/mines': typeof MinesRoute
  '/platforms': typeof PlatformsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apple' | '/conditions' | '/crash' | '/mines' | '/platforms'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apple' | '/conditions' | '/crash' | '/mines' | '/platforms'
  id:
    | '__root__'
    | '/'
    | '/apple'
    | '/conditions'
    | '/crash'
    | '/mines'
    | '/platforms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppleRoute: typeof AppleRoute
  ConditionsRoute: typeof ConditionsRoute
  CrashRoute: typeof CrashRoute
  MinesRoute: typeof MinesRoute
  PlatformsRoute: typeof PlatformsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apple': {
      id: '/apple'
      path: '/apple'
      fullPath: '/apple'
      preLoaderRoute: typeof AppleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crash': {
      id: '/crash'
      path: '/crash'
      fullPath: '/crash'
      preLoaderRoute: typeof CrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mines': {
      id: '/mines'
      path: '/mines'
      fullPath: '/mines'
      preLoaderRoute: typeof MinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platforms': {
      id: '/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof PlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppleRoute: AppleRoute,
  ConditionsRoute: ConditionsRoute,
  CrashRoute: CrashRoute,
  MinesRoute: MinesRoute,
  PlatformsRoute: PlatformsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
